apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: rustx2802/my-app:428ddf505c9cc9dcd4e8b9ffab327b2e0d1b85d9
        ports:
        - containerPort: 3000
